### ISSUE TITLE
Crashes when configured with a 0x prefixed address

### ISSUE THREAD

**Issue by jonbern** [hubiinetwork/nahmii-cli#12]
When the CLI is configured to use an address with 0x prefixing an error occurs when trying to query balances:

```
TypeError: address.replace is not a function
    at Object.importFromFile (/usr/local/lib/node_modules/striim-cli/node_modules/keythereum/index.js:516:23)
    at Object.cfg.privateKey (/usr/local/lib/node_modules/striim-cli/src/config.js:29:34)
```

**Comment by morfj** [comment]
Unable to reproduce with `striim show balance`. Call stack indicates error originates when trying to decrypt the private key which only happens in `striim pay` and `striim deposit`.

**Comment by morfj** [comment]
@jonbern can you try to reproduce after #14 has been merged and released?

**Comment by jonbern** [comment]
I have updated striim and I'm able to reproduce a similar issue (Also reproducible on v1.0.0)

```
env LOG_LEVEL=debug striim show payments
TypeError: str.startsWith is not a function
    at Object.strip0x (/usr/local/lib/node_modules/striim-cli/src/sdk/utils.js:32:13)
    at isSameAddress (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/payments.js:7:22)
    at isMyPayment (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/payments.js:20:20)
    at Array.filter (<anonymous>)
    at Object.handler (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/payments.js:28:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Unable to show pending payments.
    at Object.handler (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/payments.js:34:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is the address I'm using:
https://ropsten.etherscan.io/address/0x473a47d4ae5b86bc5897a8af1c8bea297a1399dc

Also, it does not have any striim balances, which is probably a difference compared to the address you're testing with.

**Comment by jonbern** [comment]
When querying balances:
`env LOG_LEVEL=debug striim show balance`

I get this error:

```
TypeError: address.replace is not a function
    at Object.importFromFile (/usr/local/lib/node_modules/striim-cli/node_modules/keythereum/index.js:516:23)
    at Object.cfg.privateKey (/usr/local/lib/node_modules/striim-cli/src/config.js:29:34)
    at Object.handler (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/balance.js:14:51)
    at Object.runCommand (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1059:30)
    at Object.runCommand (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/lib/command.js:197:45)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/striim-cli/src/main.js:18:4)
    at Module._compile (module.js:652:30)
Error: Unable to retrieve the balance.
    at Object.handler (/usr/local/lib/node_modules/striim-cli/src/commands/show-commands/balance.js:21:19)
    at Object.runCommand (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/lib/command.js:237:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1059:30)
    at Object.runCommand (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/lib/command.js:197:45)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1059:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/striim-cli/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/striim-cli/src/main.js:18:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by jonbern** [comment]
This is my config:

```
apiRoot: api2.dev.hubii.net
appId: 5b0809d3b04fc00010901e7f
appSecret: *******
wallet:
    address: 0x473A47d4Ae5b86bc5897A8Af1c8BeA297a1399dC
    secret: *******
```

**Comment by jacobotoll** [comment]
Is this still valid or can we close it?

**Comment by jonbern** [comment]
This is no longer an issue.
